name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Cache Nez
      id: cache-nez
      uses: actions/cache@v2
      with:
        path: "../nez"
        key: ${{ nez }}-${{ hashFiles("../nez/.git/ORIG_HEAD" }}
    - name: Install Nez
      if: steps.cache-nez.outputs.cache-hit != "true"
      run: git clone git@github.com:prime31/Nez.git ../nez
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: msbuild
    - name: Test
      run: dotnet vstest TheHarvest.Tests\bin\Debug\TheHarvest.Tests.dll
