name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Checkout Nez
      uses: actions/checkout@v2
      with:
        repository: prime31/Nez
        path: ../Nez
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: msbuild
    - name: Test
      run: dotnet vstest TheHarvest.Tests\bin\Debug\TheHarvest.Tests.dll
